import { createAgentResult } from "../core/types.js";

function guessFile(task) {
  const match = String(task || "").match(/([\w./-]+\.(?:ts|js|tsx|jsx|py|go|rs|java|md|yaml|yml|json))/i);
  return match ? match[1] : "src/feature/implementation.ts";
}

function buildPatch(filePath, task) {
  return [
    `*** Begin Patch`,
    `*** Update File: ${filePath}`,
    `@@`,
    `+// TODO: generated by CodeAgent`,
    `+// Task: ${String(task || "").slice(0, 120)}`,
    `+export function applyChange() {`,
    `+  return "implement me";`,
    `+}`,
    `*** End Patch`,
  ].join("\n");
}

export class CodeAgent {
  constructor(params = {}) {
    this.id = "code";
    this.toolProxy = params.toolProxy;
  }

  async run(task, context) {
    this.toolProxy?.assertAllowed(this.id, "read_workspace");
    this.toolProxy?.assertAllowed(this.id, "write_workspace");

    const filePath = guessFile(task);
    const patch = buildPatch(filePath, task);
    const command = `apply_patch <<'PATCH'\n${patch}\nPATCH`;

    return createAgentResult({
      status: "success",
      summary: `Prepared a focused code patch proposal for ${filePath} with minimal, reviewable changes.`,
      citations: [],
      artifacts: [
        { type: "patch", content: patch },
        { type: "command", content: command },
      ],
      memory_suggestions: [
        {
          key: `code:last_target:${context?.task_id || "unknown"}`,
          value: filePath,
          ttl: "short",
        },
      ],
      followups: ["Run TestAgent for regression safety before applying patch."],
    });
  }
}
